//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Email {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Email() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Email", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=iso-8859-9&quot; /&gt;
        ///  &lt;title&gt;Untitled Document&lt;/title&gt;
        ///  &lt;style type=&quot;text/css&quot;&gt;
        ///    .container
        ///    {
        ///      float: none;
        ///      height: auto;
        ///      width: 680px;
        ///      margin-top: 50px;
        ///      margin-right: auto;
        ///      margin-bottom: 0px;
        ///      margin-left: auto;
        ///    } [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Approval {
            get {
                return ResourceManager.GetString("Approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to 
        /// &lt;a style=&quot;text-decoration:none;&quot; href=&quot;www.trinnk.com/uyelikgiris?email=#email&amp;pagetype=1&quot;&gt;buradan&lt;/a&gt;.
        /// </summary>
        internal static string bireyseluyefirmaolmalı {
            get {
                return ResourceManager.GetString("bireyseluyefirmaolmalı", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;a style=&quot;font-size:12px; font-family:Arial; text-decoration:none;&quot; target=&quot;_blank&quot; href=&quot;#firmaduzenle#&quot;&gt;buradan&lt;/a&gt;.
        /// </summary>
        internal static string firmaduzenle {
            get {
                return ResourceManager.GetString("firmaduzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;a style=&quot;font-size:12px; font-family:Arial; text-decoration:none;&quot; target=&quot;_blank&quot; href=&quot;#firmalink#&quot;&gt;buradan&lt;/a&gt;.
        /// </summary>
        internal static string firmalink {
            get {
                return ResourceManager.GetString("firmalink", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;div style=&quot;width:auto; height:auto;&quot;&gt;#firmabilgileri#&lt;/div&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string firmaonaylanmadi {
            get {
                return ResourceManager.GetString("firmaonaylanmadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot;         ///
        ///&quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        .activitaionHeader
        ///        {
        ///            width: 970px;
        ///            height: 137px;
        ///            margin: 0px auto;
        ///            background-color: InfoText;
        ///            background-image: url(&apos;/Content/Images/activation/activationHeader.png&apos;);
        ///        }
        ///        
        ///        . [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string firmasilinmis {
            get {
                return ResourceManager.GetString("firmasilinmis", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///      .style1
        ///      {
        ///        width: 100%;
        ///      }
        /// p.MsoNormal
        ///	{margin-bottom:.0001pt;
        ///	font-size:12.0pt;
        ///	font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;
        ///	     margin-left: 0cm;
        ///        margin-right: 0cm;
        ///        margin-top: 0cm;
        ///      }
        ///      .style2
        ///      {
        ///        color: #00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string firmauyeligionay {
            get {
                return ResourceManager.GetString("firmauyeligionay", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///      .style1
        ///      {
        ///        width: 100%;
        ///      }
        /// p.MsoNormal
        ///	{margin-bottom:.0001pt;
        ///	font-size:12.0pt;
        ///	font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;
        ///	     margin-left: 0cm;
        ///        margin-right: 0cm;
        ///        margin-top: 0cm;
        ///      }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;div style= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string goldenpro {
            get {
                return ResourceManager.GetString("goldenpro", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;a style=&quot;font-size:12px; font-family:Arial; text-decoration:none;&quot; target=&quot;_blank&quot; href=&quot;#ilangiris#&quot;&gt;buradan&lt;/a&gt;.
        /// </summary>
        internal static string ilanduzeltme {
            get {
                return ResourceManager.GetString("ilanduzeltme", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;link href=&quot;http://www.trinnk.com/content/mastersite.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        .activitaionHeader
        ///        {
        ///            width: 970px;
        ///            height: 137px;
        ///            margin: 0px auto;
        ///            background-color: InfoText;
        ///            ba [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ilanekle {
            get {
                return ResourceManager.GetString("ilanekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Trinnk.com&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;div style=&quot;width:auto; height:auto;&quot;&gt;#ilanbilgileri#&lt;/div&gt;
        ///&lt;br /&gt;
        ///
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string ilanonaylanmadi {
            get {
                return ResourceManager.GetString("ilanonaylanmadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;a style=&quot;font-size:12px; font-family:Arial; text-decoration:none;&quot; target=&quot;_blank&quot; href=&quot;#urunlink#&quot;&gt; buraya&lt;/a&gt;.
        /// </summary>
        internal static string linkkopru {
            get {
                return ResourceManager.GetString("linkkopru", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;a style=&quot;font-size:12px; font-family:Arial; text-decoration:none;&quot; target=&quot;_blank&quot; href=&quot;#urunlink#&quot;&gt; #urunadi#&lt;/a&gt;.
        /// </summary>
        internal static string linkurunadi {
            get {
                return ResourceManager.GetString("linkurunadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to #aciklama#.
        /// </summary>
        internal static string masterpage {
            get {
                return ResourceManager.GetString("masterpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;makina türkiye&lt;/title&gt; 
        ///     &lt;style type=&quot;text/css&quot;&gt;
        ///     .container
        ///    {
        ///      float: none;
        ///      height: auto;
        ///      width: 680px;
        ///      margin-top: 50px;
        ///      margin-right: auto;
        ///      margin-bottom: 0px;
        ///      margin-left: auto;
        ///      border: solid 2px #99D6DD;
        ///    }
        ///    .logo
        ///    {
        ///      background-ima [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string memberbilgilendirme {
            get {
                return ResourceManager.GetString("memberbilgilendirme", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;br/&gt;&lt;div class=&quot;container&quot;&gt;
        ///    &lt;div class=&quot;logo&quot;&gt;
        ///    &lt;/div&gt;
        ///    &lt;div class=&quot;yazi&quot;&gt;
        ///      trinnk.com kayıt işleminizi tamamlamak için, aşağıdakionay butonuna tıklayınız!&lt;/div&gt;
        ///    &lt;div class=&quot;onaybutton&quot;&gt;
        ///      &lt;a href=&quot;#OnayLink#&quot;&gt;Üyeliğimi Onaylıyorum!&lt;/a&gt;&lt;/div&gt;
        ///    &lt;hr /&gt;
        ///    &lt;div class=&quot;yazi2&quot;&gt;
        ///      Yukarıdaki link çalışmaz ise;&lt;/div&gt;
        ///    &lt;div class=&quot;yazi3&quot;&gt;
        ///      1. Onay Kodu: &lt;span class=&quot;yazi4&quot;&gt;#OnayKodu#&lt;/span&gt;&lt;/div&gt;
        ///    &lt;div class=&quot;yazi3&quot;&gt;
        ///      2. Aşağıdaki linki tarayıcınız [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string onaymailitekrar {
            get {
                return ResourceManager.GetString("onaymailitekrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ürün onay.
        /// </summary>
        internal static string ProductApproval {
            get {
                return ResourceManager.GetString("ProductApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;link href=&quot;http://www.trinnk.com/content/mastersite.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        .activitaionHeader
        ///        {
        ///            width: 970px;
        ///            height: 137px;
        ///            margin: 0px auto;
        ///            background-color: InfoText;
        ///            ba [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProductDesc {
            get {
                return ResourceManager.GetString("ProductDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;link href=&quot;http://www.trinnk.com/content/mastersite.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        .activitaionHeader
        ///        {
        ///            width: 970px;
        ///            height: 137px;
        ///            margin: 0px auto;
        ///            background-color: InfoText;
        ///            ba [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StoreDesc {
            get {
                return ResourceManager.GetString("StoreDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///      .style1
        ///      {
        ///        width: 100%;
        ///      }
        ///      .style2
        ///      {
        ///        color: #000000;
        ///      }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///  &lt;table class=&quot;style1&quot;&gt;
        ///    &lt;tr&gt;
        ///      &lt;td&gt;
        ///        &lt;span lang=&quot;EN-US&quot; style=&quot;font-size:12.0pt;font-family:
        ///&amp;quot;Times New Roman&amp;quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string uyelikonaylanmadi {
            get {
                return ResourceManager.GetString("uyelikonaylanmadi", resourceCulture);
            }
        }
    }
}
