//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Email {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Email() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Email", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=iso-8859-9&quot; /&gt;
        ///  &lt;title&gt;Untitled Document&lt;/title&gt;
        ///  &lt;style type=&quot;text/css&quot;&gt;
        ///    .container
        ///    {
        ///      float: none;
        ///      height: auto;
        ///      width: 680px;
        ///      margin-top: 50px;
        ///      margin-right: auto;
        ///      margin-bottom: 0px;
        ///      margin-left: auto;
        ///    }
        ///    .logo
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Approval {
            get {
                return ResourceManager.GetString("Approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///      .style1
        ///      {
        ///        width: 100%;
        ///      }
        ///      .style2
        ///      {
        ///        width: 338px;
        ///      }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;position:inherit;&quot;&gt;
        ///
        ///  &lt;table class=&quot;style1&quot;&gt;
        ///    &lt;tr&gt;
        ///      &lt;td class=&quot;style2&quot;&gt;
        ///        kullanıcı adı:&lt;/td&gt;
        ///      &lt;td&gt;
        ///        #kullanicimiz#&lt;/td&gt;
        ///    &lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bilgimakinasayfası {
            get {
                return ResourceManager.GetString("bilgimakinasayfası", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///      .style1
        ///      {
        ///        width: 100%;
        ///      }
        /// p.MsoNormal
        ///	{margin-bottom:.0001pt;
        ///	font-size:12.0pt;
        ///	font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;
        ///	     margin-left: 0cm;
        ///        margin-right: 0cm;
        ///        margin-top: 0cm;
        ///      }
        ///      .style2
        ///      {
        ///        color: #000000;
        ///      }
        ///    &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bireyseluyelik {
            get {
                return ResourceManager.GetString("bireyseluyelik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///	&lt;head&gt;
        ///        &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///        &lt;title&gt;Trinnk.Com - Şifremi Unuttum&lt;/title&gt;
        ///        &lt;style type=&quot;text/css&quot;&gt;
        ///			/* /\/\/\/\/\/\/\/\/ CLIENT-SPECIFIC STYLES /\/\/\/\/\/\/\/\/ */
        ///			#outlook a{padding:0;} /* Force Outlook to provide a &quot;view in browser&quot; message */
        ///			.Read [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ForgetPassord {
            get {
                return ResourceManager.GetString("ForgetPassord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///      .style1
        ///      {
        ///        width: 100%;
        ///      }
        /// p.MsoNormal
        ///	{margin-bottom:.0001pt;
        ///	font-size:12.0pt;
        ///	font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;
        ///	     margin-left: 0cm;
        ///        margin-right: 0cm;
        ///        margin-top: 0cm;
        ///      }
        ///      .style2
        ///      {
        ///        color: #000000;
        ///      }
        ///    &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Hizliuyelik {
            get {
                return ResourceManager.GetString("Hizliuyelik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///     .style2
        ///      {
        ///        color: #6600CC;
        ///      }
        ///    &lt;/style&gt;
        ///
        ///&lt;/head&gt;
        ///&lt;body style=&quot;width:770px;height:230px;&quot;&gt;
        ///
        ///
        ///  &lt;table style=&quot;margin:30px; width:700px; height:200px;&quot;&gt;
        ///    &lt;tr style=&quot;width:670px;height:10px;&quot;&gt;
        ///      &lt;td style=&quot;width:650px;height:9px;&quot;&gt;
        ///      Makinatürkiye.com kulla [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mesajınızvar {
            get {
                return ResourceManager.GetString("mesajınızvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///	&lt;head&gt;
        ///        &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///        &lt;title&gt;Trinnk.Com - Şifremi Unuttum&lt;/title&gt;
        ///        &lt;style type=&quot;text/css&quot;&gt;
        ///			/* /\/\/\/\/\/\/\/\/ CLIENT-SPECIFIC STYLES /\/\/\/\/\/\/\/\/ */
        ///			#outlook a{padding:0;} /* Force Outlook to provide a &quot;view in browser&quot; message */
        ///			.Read [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PasswordRecreated {
            get {
                return ResourceManager.GetString("PasswordRecreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ürün onay.
        /// </summary>
        internal static string ProductApproval {
            get {
                return ResourceManager.GetString("ProductApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;link href=&quot;http://www.makinaturkiye.com/content/mastersite.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        .activitaionHeader
        ///        {
        ///            width: 970px;
        ///            height: 137px;
        ///            margin: 0px auto;
        ///            background-color: InfoText;
        ///            background-ima [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProductDesc {
            get {
                return ResourceManager.GetString("ProductDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///      .style1
        ///      {
        ///        width: 100%;
        ///      }
        /// p.MsoNormal
        ///	{margin-bottom:.0001pt;
        ///	font-size:12.0pt;
        ///	font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;
        ///	     margin-left: 0cm;
        ///        margin-right: 0cm;
        ///        margin-top: 0cm;
        ///      }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;&lt;div style=&quot;align:center&quot;&gt;&lt;img s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StoreDesc {
            get {
                return ResourceManager.GetString("StoreDesc", resourceCulture);
            }
        }
    }
}
