//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BulkImageResizeTool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\inetpub\\vhosts\\makinaturkiye.com\\httpdocs\\UserFiles\\Images\\Product\\")]
        public string OldImagePath {
            get {
                return ((string)(this["OldImagePath"]));
            }
            set {
                this["OldImagePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("900x675;400x300;100x75;100x*")]
        public string ThumbSizes {
            get {
                return ((string)(this["ThumbSizes"]));
            }
            set {
                this["ThumbSizes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\inetpub\\wwwroot\\testImages\\")]
        public string MainImagePath {
            get {
                return ((string)(this["MainImagePath"]));
            }
            set {
                this["MainImagePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\inetpub\\vhosts\\makinaturkiye.com\\httpdocs\\UserFiles\\Images\\StoreLogo\\")]
        public string OldStoreLogoImagePath {
            get {
                return ((string)(this["OldStoreLogoImagePath"]));
            }
            set {
                this["OldStoreLogoImagePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\inetpub\\vhosts\\makinaturkiye.com\\httpdocs\\UserFiles\\Images\\StoreProfilePicture" +
            "\\")]
        public string OldStoreProfileImagePath {
            get {
                return ((string)(this["OldStoreProfileImagePath"]));
            }
            set {
                this["OldStoreProfileImagePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300x200;100x100")]
        public string StoreLogoThumbSizes {
            get {
                return ((string)(this["StoreLogoThumbSizes"]));
            }
            set {
                this["StoreLogoThumbSizes"] = value;
            }
        }
    }
}
