//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace BulkImageResizeTool
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MTEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MTEntities object using the connection string found in the 'MTEntities' section of the application configuration file.
        /// </summary>
        public MTEntities() : base("name=MTEntities", "MTEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MTEntities object.
        /// </summary>
        public MTEntities(string connectionString) : base(connectionString, "MTEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MTEntities object.
        /// </summary>
        public MTEntities(EntityConnection connection) : base(connection, "MTEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Picture> Picture
        {
            get
            {
                if ((_Picture == null))
                {
                    _Picture = base.CreateObjectSet<Picture>("Picture");
                }
                return _Picture;
            }
        }
        private ObjectSet<Picture> _Picture;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Product> Product
        {
            get
            {
                if ((_Product == null))
                {
                    _Product = base.CreateObjectSet<Product>("Product");
                }
                return _Product;
            }
        }
        private ObjectSet<Product> _Product;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ImageProcessLog> ImageProcessLogs
        {
            get
            {
                if ((_ImageProcessLogs == null))
                {
                    _ImageProcessLogs = base.CreateObjectSet<ImageProcessLog>("ImageProcessLogs");
                }
                return _ImageProcessLogs;
            }
        }
        private ObjectSet<ImageProcessLog> _ImageProcessLogs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Store> Stores
        {
            get
            {
                if ((_Stores == null))
                {
                    _Stores = base.CreateObjectSet<Store>("Stores");
                }
                return _Stores;
            }
        }
        private ObjectSet<Store> _Stores;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Picture EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPicture(Picture picture)
        {
            base.AddObject("Picture", picture);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Product EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProduct(Product product)
        {
            base.AddObject("Product", product);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ImageProcessLogs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToImageProcessLogs(ImageProcessLog imageProcessLog)
        {
            base.AddObject("ImageProcessLogs", imageProcessLog);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Stores EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStores(Store store)
        {
            base.AddObject("Stores", store);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MTModel", Name="ImageProcessLog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ImageProcessLog : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ImageProcessLog object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="message">Initial value of the Message property.</param>
        public static ImageProcessLog CreateImageProcessLog(global::System.Int32 id, global::System.String message)
        {
            ImageProcessLog imageProcessLog = new ImageProcessLog();
            imageProcessLog.id = id;
            imageProcessLog.Message = message;
            return imageProcessLog;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ProductId
        {
            get
            {
                return _ProductId;
            }
            set
            {
                OnProductIdChanging(value);
                ReportPropertyChanging("ProductId");
                _ProductId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductId");
                OnProductIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ProductId;
        partial void OnProductIdChanging(Nullable<global::System.Int32> value);
        partial void OnProductIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PictureId
        {
            get
            {
                return _PictureId;
            }
            set
            {
                OnPictureIdChanging(value);
                ReportPropertyChanging("PictureId");
                _PictureId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PictureId");
                OnPictureIdChanged();
            }
        }
        private Nullable<global::System.Int32> _PictureId;
        partial void OnPictureIdChanging(Nullable<global::System.Int32> value);
        partial void OnPictureIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                OnMessageChanging(value);
                ReportPropertyChanging("Message");
                _Message = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Message");
                OnMessageChanged();
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedOn
        {
            get
            {
                return _CreatedOn;
            }
            set
            {
                OnCreatedOnChanging(value);
                ReportPropertyChanging("CreatedOn");
                _CreatedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedOn");
                OnCreatedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedOn;
        partial void OnCreatedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedOnChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MTModel", Name="Picture")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Picture : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Picture object.
        /// </summary>
        /// <param name="pictureId">Initial value of the PictureId property.</param>
        public static Picture CreatePicture(global::System.Int32 pictureId)
        {
            Picture picture = new Picture();
            picture.PictureId = pictureId;
            return picture;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PictureId
        {
            get
            {
                return _PictureId;
            }
            set
            {
                if (_PictureId != value)
                {
                    OnPictureIdChanging(value);
                    ReportPropertyChanging("PictureId");
                    _PictureId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PictureId");
                    OnPictureIdChanged();
                }
            }
        }
        private global::System.Int32 _PictureId;
        partial void OnPictureIdChanging(global::System.Int32 value);
        partial void OnPictureIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ProductId
        {
            get
            {
                return _ProductId;
            }
            set
            {
                OnProductIdChanging(value);
                ReportPropertyChanging("ProductId");
                _ProductId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductId");
                OnProductIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ProductId;
        partial void OnProductIdChanging(Nullable<global::System.Int32> value);
        partial void OnProductIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MainPartyId
        {
            get
            {
                return _MainPartyId;
            }
            set
            {
                OnMainPartyIdChanging(value);
                ReportPropertyChanging("MainPartyId");
                _MainPartyId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MainPartyId");
                OnMainPartyIdChanged();
            }
        }
        private Nullable<global::System.Int32> _MainPartyId;
        partial void OnMainPartyIdChanging(Nullable<global::System.Int32> value);
        partial void OnMainPartyIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PictureName
        {
            get
            {
                return _PictureName;
            }
            set
            {
                OnPictureNameChanging(value);
                ReportPropertyChanging("PictureName");
                _PictureName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PictureName");
                OnPictureNameChanged();
            }
        }
        private global::System.String _PictureName;
        partial void OnPictureNameChanging(global::System.String value);
        partial void OnPictureNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OldPath
        {
            get
            {
                return _OldPath;
            }
            set
            {
                OnOldPathChanging(value);
                ReportPropertyChanging("OldPath");
                _OldPath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OldPath");
                OnOldPathChanged();
            }
        }
        private global::System.String _OldPath;
        partial void OnOldPathChanging(global::System.String value);
        partial void OnOldPathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PicturePath
        {
            get
            {
                return _PicturePath;
            }
            set
            {
                OnPicturePathChanging(value);
                ReportPropertyChanging("PicturePath");
                _PicturePath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PicturePath");
                OnPicturePathChanged();
            }
        }
        private global::System.String _PicturePath;
        partial void OnPicturePathChanging(global::System.String value);
        partial void OnPicturePathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StoreDealerId
        {
            get
            {
                return _StoreDealerId;
            }
            set
            {
                OnStoreDealerIdChanging(value);
                ReportPropertyChanging("StoreDealerId");
                _StoreDealerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StoreDealerId");
                OnStoreDealerIdChanged();
            }
        }
        private Nullable<global::System.Int32> _StoreDealerId;
        partial void OnStoreDealerIdChanging(Nullable<global::System.Int32> value);
        partial void OnStoreDealerIdChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MTModel", Name="Product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Product : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="productId">Initial value of the ProductId property.</param>
        public static Product CreateProduct(global::System.Int32 productId)
        {
            Product product = new Product();
            product.ProductId = productId;
            return product;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProductId
        {
            get
            {
                return _ProductId;
            }
            set
            {
                if (_ProductId != value)
                {
                    OnProductIdChanging(value);
                    ReportPropertyChanging("ProductId");
                    _ProductId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProductId");
                    OnProductIdChanged();
                }
            }
        }
        private global::System.Int32 _ProductId;
        partial void OnProductIdChanging(global::System.Int32 value);
        partial void OnProductIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CategoryId
        {
            get
            {
                return _CategoryId;
            }
            set
            {
                OnCategoryIdChanging(value);
                ReportPropertyChanging("CategoryId");
                _CategoryId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CategoryId");
                OnCategoryIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CategoryId;
        partial void OnCategoryIdChanging(Nullable<global::System.Int32> value);
        partial void OnCategoryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ProductGroupId
        {
            get
            {
                return _ProductGroupId;
            }
            set
            {
                OnProductGroupIdChanging(value);
                ReportPropertyChanging("ProductGroupId");
                _ProductGroupId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductGroupId");
                OnProductGroupIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ProductGroupId;
        partial void OnProductGroupIdChanging(Nullable<global::System.Int32> value);
        partial void OnProductGroupIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BrandId
        {
            get
            {
                return _BrandId;
            }
            set
            {
                OnBrandIdChanging(value);
                ReportPropertyChanging("BrandId");
                _BrandId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BrandId");
                OnBrandIdChanged();
            }
        }
        private Nullable<global::System.Int32> _BrandId;
        partial void OnBrandIdChanging(Nullable<global::System.Int32> value);
        partial void OnBrandIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SeriesId
        {
            get
            {
                return _SeriesId;
            }
            set
            {
                OnSeriesIdChanging(value);
                ReportPropertyChanging("SeriesId");
                _SeriesId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SeriesId");
                OnSeriesIdChanged();
            }
        }
        private Nullable<global::System.Int32> _SeriesId;
        partial void OnSeriesIdChanging(Nullable<global::System.Int32> value);
        partial void OnSeriesIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ModelId
        {
            get
            {
                return _ModelId;
            }
            set
            {
                OnModelIdChanging(value);
                ReportPropertyChanging("ModelId");
                _ModelId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModelId");
                OnModelIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ModelId;
        partial void OnModelIdChanging(Nullable<global::System.Int32> value);
        partial void OnModelIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MainPartyId
        {
            get
            {
                return _MainPartyId;
            }
            set
            {
                OnMainPartyIdChanging(value);
                ReportPropertyChanging("MainPartyId");
                _MainPartyId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MainPartyId");
                OnMainPartyIdChanged();
            }
        }
        private Nullable<global::System.Int32> _MainPartyId;
        partial void OnMainPartyIdChanging(Nullable<global::System.Int32> value);
        partial void OnMainPartyIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CountryId
        {
            get
            {
                return _CountryId;
            }
            set
            {
                OnCountryIdChanging(value);
                ReportPropertyChanging("CountryId");
                _CountryId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CountryId");
                OnCountryIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CountryId;
        partial void OnCountryIdChanging(Nullable<global::System.Int32> value);
        partial void OnCountryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CityId
        {
            get
            {
                return _CityId;
            }
            set
            {
                OnCityIdChanging(value);
                ReportPropertyChanging("CityId");
                _CityId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CityId");
                OnCityIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CityId;
        partial void OnCityIdChanging(Nullable<global::System.Int32> value);
        partial void OnCityIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LocalityId
        {
            get
            {
                return _LocalityId;
            }
            set
            {
                OnLocalityIdChanging(value);
                ReportPropertyChanging("LocalityId");
                _LocalityId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LocalityId");
                OnLocalityIdChanged();
            }
        }
        private Nullable<global::System.Int32> _LocalityId;
        partial void OnLocalityIdChanging(Nullable<global::System.Int32> value);
        partial void OnLocalityIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TownId
        {
            get
            {
                return _TownId;
            }
            set
            {
                OnTownIdChanging(value);
                ReportPropertyChanging("TownId");
                _TownId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TownId");
                OnTownIdChanged();
            }
        }
        private Nullable<global::System.Int32> _TownId;
        partial void OnTownIdChanging(Nullable<global::System.Int32> value);
        partial void OnTownIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DistrictId
        {
            get
            {
                return _DistrictId;
            }
            set
            {
                OnDistrictIdChanging(value);
                ReportPropertyChanging("DistrictId");
                _DistrictId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DistrictId");
                OnDistrictIdChanged();
            }
        }
        private Nullable<global::System.Int32> _DistrictId;
        partial void OnDistrictIdChanging(Nullable<global::System.Int32> value);
        partial void OnDistrictIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> CurrencyId
        {
            get
            {
                return _CurrencyId;
            }
            set
            {
                OnCurrencyIdChanging(value);
                ReportPropertyChanging("CurrencyId");
                _CurrencyId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CurrencyId");
                OnCurrencyIdChanged();
            }
        }
        private Nullable<global::System.Byte> _CurrencyId;
        partial void OnCurrencyIdChanging(Nullable<global::System.Byte> value);
        partial void OnCurrencyIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductNo
        {
            get
            {
                return _ProductNo;
            }
            set
            {
                OnProductNoChanging(value);
                ReportPropertyChanging("ProductNo");
                _ProductNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductNo");
                OnProductNoChanged();
            }
        }
        private global::System.String _ProductNo;
        partial void OnProductNoChanging(global::System.String value);
        partial void OnProductNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CategoryTreeName
        {
            get
            {
                return _CategoryTreeName;
            }
            set
            {
                OnCategoryTreeNameChanging(value);
                ReportPropertyChanging("CategoryTreeName");
                _CategoryTreeName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CategoryTreeName");
                OnCategoryTreeNameChanged();
            }
        }
        private global::System.String _CategoryTreeName;
        partial void OnCategoryTreeNameChanging(global::System.String value);
        partial void OnCategoryTreeNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductName
        {
            get
            {
                return _ProductName;
            }
            set
            {
                OnProductNameChanging(value);
                ReportPropertyChanging("ProductName");
                _ProductName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductName");
                OnProductNameChanged();
            }
        }
        private global::System.String _ProductName;
        partial void OnProductNameChanging(global::System.String value);
        partial void OnProductNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ProductPrice
        {
            get
            {
                return _ProductPrice;
            }
            set
            {
                OnProductPriceChanging(value);
                ReportPropertyChanging("ProductPrice");
                _ProductPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductPrice");
                OnProductPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _ProductPrice;
        partial void OnProductPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnProductPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductType
        {
            get
            {
                return _ProductType;
            }
            set
            {
                OnProductTypeChanging(value);
                ReportPropertyChanging("ProductType");
                _ProductType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductType");
                OnProductTypeChanged();
            }
        }
        private global::System.String _ProductType;
        partial void OnProductTypeChanging(global::System.String value);
        partial void OnProductTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductSalesType
        {
            get
            {
                return _ProductSalesType;
            }
            set
            {
                OnProductSalesTypeChanging(value);
                ReportPropertyChanging("ProductSalesType");
                _ProductSalesType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductSalesType");
                OnProductSalesTypeChanged();
            }
        }
        private global::System.String _ProductSalesType;
        partial void OnProductSalesTypeChanging(global::System.String value);
        partial void OnProductSalesTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductDescription
        {
            get
            {
                return _ProductDescription;
            }
            set
            {
                OnProductDescriptionChanging(value);
                ReportPropertyChanging("ProductDescription");
                _ProductDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductDescription");
                OnProductDescriptionChanged();
            }
        }
        private global::System.String _ProductDescription;
        partial void OnProductDescriptionChanging(global::System.String value);
        partial void OnProductDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ProductRecordDate
        {
            get
            {
                return _ProductRecordDate;
            }
            set
            {
                OnProductRecordDateChanging(value);
                ReportPropertyChanging("ProductRecordDate");
                _ProductRecordDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductRecordDate");
                OnProductRecordDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ProductRecordDate;
        partial void OnProductRecordDateChanging(Nullable<global::System.DateTime> value);
        partial void OnProductRecordDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> ProductShowcase
        {
            get
            {
                return _ProductShowcase;
            }
            set
            {
                OnProductShowcaseChanging(value);
                ReportPropertyChanging("ProductShowcase");
                _ProductShowcase = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductShowcase");
                OnProductShowcaseChanged();
            }
        }
        private Nullable<global::System.Boolean> _ProductShowcase;
        partial void OnProductShowcaseChanging(Nullable<global::System.Boolean> value);
        partial void OnProductShowcaseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ProductAdvertBeginDate
        {
            get
            {
                return _ProductAdvertBeginDate;
            }
            set
            {
                OnProductAdvertBeginDateChanging(value);
                ReportPropertyChanging("ProductAdvertBeginDate");
                _ProductAdvertBeginDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductAdvertBeginDate");
                OnProductAdvertBeginDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ProductAdvertBeginDate;
        partial void OnProductAdvertBeginDateChanging(Nullable<global::System.DateTime> value);
        partial void OnProductAdvertBeginDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ProductAdvertEndDate
        {
            get
            {
                return _ProductAdvertEndDate;
            }
            set
            {
                OnProductAdvertEndDateChanging(value);
                ReportPropertyChanging("ProductAdvertEndDate");
                _ProductAdvertEndDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductAdvertEndDate");
                OnProductAdvertEndDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ProductAdvertEndDate;
        partial void OnProductAdvertEndDateChanging(Nullable<global::System.DateTime> value);
        partial void OnProductAdvertEndDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductStatu
        {
            get
            {
                return _ProductStatu;
            }
            set
            {
                OnProductStatuChanging(value);
                ReportPropertyChanging("ProductStatu");
                _ProductStatu = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductStatu");
                OnProductStatuChanged();
            }
        }
        private global::System.String _ProductStatu;
        partial void OnProductStatuChanging(global::System.String value);
        partial void OnProductStatuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> ProductActiveType
        {
            get
            {
                return _ProductActiveType;
            }
            set
            {
                OnProductActiveTypeChanging(value);
                ReportPropertyChanging("ProductActiveType");
                _ProductActiveType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductActiveType");
                OnProductActiveTypeChanged();
            }
        }
        private Nullable<global::System.Byte> _ProductActiveType;
        partial void OnProductActiveTypeChanging(Nullable<global::System.Byte> value);
        partial void OnProductActiveTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OtherBrand
        {
            get
            {
                return _OtherBrand;
            }
            set
            {
                OnOtherBrandChanging(value);
                ReportPropertyChanging("OtherBrand");
                _OtherBrand = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OtherBrand");
                OnOtherBrandChanged();
            }
        }
        private global::System.String _OtherBrand;
        partial void OnOtherBrandChanging(global::System.String value);
        partial void OnOtherBrandChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OtherModel
        {
            get
            {
                return _OtherModel;
            }
            set
            {
                OnOtherModelChanging(value);
                ReportPropertyChanging("OtherModel");
                _OtherModel = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OtherModel");
                OnOtherModelChanged();
            }
        }
        private global::System.String _OtherModel;
        partial void OnOtherModelChanging(global::System.String value);
        partial void OnOtherModelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ModelYear
        {
            get
            {
                return _ModelYear;
            }
            set
            {
                OnModelYearChanging(value);
                ReportPropertyChanging("ModelYear");
                _ModelYear = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModelYear");
                OnModelYearChanged();
            }
        }
        private Nullable<global::System.Int32> _ModelYear;
        partial void OnModelYearChanging(Nullable<global::System.Int32> value);
        partial void OnModelYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> ViewCount
        {
            get
            {
                return _ViewCount;
            }
            set
            {
                OnViewCountChanging(value);
                ReportPropertyChanging("ViewCount");
                _ViewCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ViewCount");
                OnViewCountChanged();
            }
        }
        private Nullable<global::System.Int64> _ViewCount;
        partial void OnViewCountChanging(Nullable<global::System.Int64> value);
        partial void OnViewCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastViewDate
        {
            get
            {
                return _LastViewDate;
            }
            set
            {
                OnLastViewDateChanging(value);
                ReportPropertyChanging("LastViewDate");
                _LastViewDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastViewDate");
                OnLastViewDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastViewDate;
        partial void OnLastViewDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastViewDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BriefDetail
        {
            get
            {
                return _BriefDetail;
            }
            set
            {
                OnBriefDetailChanging(value);
                ReportPropertyChanging("BriefDetail");
                _BriefDetail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BriefDetail");
                OnBriefDetailChanged();
            }
        }
        private global::System.String _BriefDetail;
        partial void OnBriefDetailChanging(global::System.String value);
        partial void OnBriefDetailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> ProductActive
        {
            get
            {
                return _ProductActive;
            }
            set
            {
                OnProductActiveChanging(value);
                ReportPropertyChanging("ProductActive");
                _ProductActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductActive");
                OnProductActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _ProductActive;
        partial void OnProductActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnProductActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> MoneyCondition
        {
            get
            {
                return _MoneyCondition;
            }
            set
            {
                OnMoneyConditionChanging(value);
                ReportPropertyChanging("MoneyCondition");
                _MoneyCondition = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MoneyCondition");
                OnMoneyConditionChanged();
            }
        }
        private Nullable<global::System.Boolean> _MoneyCondition;
        partial void OnMoneyConditionChanging(Nullable<global::System.Boolean> value);
        partial void OnMoneyConditionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ProductLastUpdate
        {
            get
            {
                return _ProductLastUpdate;
            }
            set
            {
                OnProductLastUpdateChanging(value);
                ReportPropertyChanging("ProductLastUpdate");
                _ProductLastUpdate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductLastUpdate");
                OnProductLastUpdateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ProductLastUpdate;
        partial void OnProductLastUpdateChanging(Nullable<global::System.DateTime> value);
        partial void OnProductLastUpdateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> SingularViewCount
        {
            get
            {
                return _SingularViewCount;
            }
            set
            {
                OnSingularViewCountChanging(value);
                ReportPropertyChanging("SingularViewCount");
                _SingularViewCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SingularViewCount");
                OnSingularViewCountChanged();
            }
        }
        private Nullable<global::System.Int64> _SingularViewCount;
        partial void OnSingularViewCountChanging(Nullable<global::System.Int64> value);
        partial void OnSingularViewCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> productrate
        {
            get
            {
                return _productrate;
            }
            set
            {
                OnproductrateChanging(value);
                ReportPropertyChanging("productrate");
                _productrate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("productrate");
                OnproductrateChanged();
            }
        }
        private Nullable<global::System.Decimal> _productrate;
        partial void OnproductrateChanging(Nullable<global::System.Decimal> value);
        partial void OnproductrateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MenseiId
        {
            get
            {
                return _MenseiId;
            }
            set
            {
                OnMenseiIdChanging(value);
                ReportPropertyChanging("MenseiId");
                _MenseiId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MenseiId");
                OnMenseiIdChanged();
            }
        }
        private Nullable<global::System.Int32> _MenseiId;
        partial void OnMenseiIdChanging(Nullable<global::System.Int32> value);
        partial void OnMenseiIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OrderStatus
        {
            get
            {
                return _OrderStatus;
            }
            set
            {
                OnOrderStatusChanging(value);
                ReportPropertyChanging("OrderStatus");
                _OrderStatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderStatus");
                OnOrderStatusChanged();
            }
        }
        private Nullable<global::System.Int32> _OrderStatus;
        partial void OnOrderStatusChanging(Nullable<global::System.Int32> value);
        partial void OnOrderStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> ReadyforSale
        {
            get
            {
                return _ReadyforSale;
            }
            set
            {
                OnReadyforSaleChanging(value);
                ReportPropertyChanging("ReadyforSale");
                _ReadyforSale = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReadyforSale");
                OnReadyforSaleChanged();
            }
        }
        private Nullable<global::System.Boolean> _ReadyforSale;
        partial void OnReadyforSaleChanging(Nullable<global::System.Boolean> value);
        partial void OnReadyforSaleChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MTModel", Name="Store")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Store : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Store object.
        /// </summary>
        /// <param name="mainPartyId">Initial value of the MainPartyId property.</param>
        public static Store CreateStore(global::System.Int32 mainPartyId)
        {
            Store store = new Store();
            store.MainPartyId = mainPartyId;
            return store;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MainPartyId
        {
            get
            {
                return _MainPartyId;
            }
            set
            {
                if (_MainPartyId != value)
                {
                    OnMainPartyIdChanging(value);
                    ReportPropertyChanging("MainPartyId");
                    _MainPartyId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MainPartyId");
                    OnMainPartyIdChanged();
                }
            }
        }
        private global::System.Int32 _MainPartyId;
        partial void OnMainPartyIdChanging(global::System.Int32 value);
        partial void OnMainPartyIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PacketId
        {
            get
            {
                return _PacketId;
            }
            set
            {
                OnPacketIdChanging(value);
                ReportPropertyChanging("PacketId");
                _PacketId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PacketId");
                OnPacketIdChanged();
            }
        }
        private Nullable<global::System.Int32> _PacketId;
        partial void OnPacketIdChanging(Nullable<global::System.Int32> value);
        partial void OnPacketIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StoreNo
        {
            get
            {
                return _StoreNo;
            }
            set
            {
                OnStoreNoChanging(value);
                ReportPropertyChanging("StoreNo");
                _StoreNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StoreNo");
                OnStoreNoChanged();
            }
        }
        private global::System.String _StoreNo;
        partial void OnStoreNoChanging(global::System.String value);
        partial void OnStoreNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StoreName
        {
            get
            {
                return _StoreName;
            }
            set
            {
                OnStoreNameChanging(value);
                ReportPropertyChanging("StoreName");
                _StoreName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StoreName");
                OnStoreNameChanged();
            }
        }
        private global::System.String _StoreName;
        partial void OnStoreNameChanging(global::System.String value);
        partial void OnStoreNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StoreEMail
        {
            get
            {
                return _StoreEMail;
            }
            set
            {
                OnStoreEMailChanging(value);
                ReportPropertyChanging("StoreEMail");
                _StoreEMail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StoreEMail");
                OnStoreEMailChanged();
            }
        }
        private global::System.String _StoreEMail;
        partial void OnStoreEMailChanging(global::System.String value);
        partial void OnStoreEMailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StoreWeb
        {
            get
            {
                return _StoreWeb;
            }
            set
            {
                OnStoreWebChanging(value);
                ReportPropertyChanging("StoreWeb");
                _StoreWeb = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StoreWeb");
                OnStoreWebChanged();
            }
        }
        private global::System.String _StoreWeb;
        partial void OnStoreWebChanging(global::System.String value);
        partial void OnStoreWebChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OldStoreLogo
        {
            get
            {
                return _OldStoreLogo;
            }
            set
            {
                OnOldStoreLogoChanging(value);
                ReportPropertyChanging("OldStoreLogo");
                _OldStoreLogo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OldStoreLogo");
                OnOldStoreLogoChanged();
            }
        }
        private global::System.String _OldStoreLogo;
        partial void OnOldStoreLogoChanging(global::System.String value);
        partial void OnOldStoreLogoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StoreLogo
        {
            get
            {
                return _StoreLogo;
            }
            set
            {
                OnStoreLogoChanging(value);
                ReportPropertyChanging("StoreLogo");
                _StoreLogo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StoreLogo");
                OnStoreLogoChanged();
            }
        }
        private global::System.String _StoreLogo;
        partial void OnStoreLogoChanging(global::System.String value);
        partial void OnStoreLogoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> StoreActiveType
        {
            get
            {
                return _StoreActiveType;
            }
            set
            {
                OnStoreActiveTypeChanging(value);
                ReportPropertyChanging("StoreActiveType");
                _StoreActiveType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StoreActiveType");
                OnStoreActiveTypeChanged();
            }
        }
        private Nullable<global::System.Byte> _StoreActiveType;
        partial void OnStoreActiveTypeChanging(Nullable<global::System.Byte> value);
        partial void OnStoreActiveTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StorePacketBeginDate
        {
            get
            {
                return _StorePacketBeginDate;
            }
            set
            {
                OnStorePacketBeginDateChanging(value);
                ReportPropertyChanging("StorePacketBeginDate");
                _StorePacketBeginDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StorePacketBeginDate");
                OnStorePacketBeginDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _StorePacketBeginDate;
        partial void OnStorePacketBeginDateChanging(Nullable<global::System.DateTime> value);
        partial void OnStorePacketBeginDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StorePacketEndDate
        {
            get
            {
                return _StorePacketEndDate;
            }
            set
            {
                OnStorePacketEndDateChanging(value);
                ReportPropertyChanging("StorePacketEndDate");
                _StorePacketEndDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StorePacketEndDate");
                OnStorePacketEndDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _StorePacketEndDate;
        partial void OnStorePacketEndDateChanging(Nullable<global::System.DateTime> value);
        partial void OnStorePacketEndDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StoreAbout
        {
            get
            {
                return _StoreAbout;
            }
            set
            {
                OnStoreAboutChanging(value);
                ReportPropertyChanging("StoreAbout");
                _StoreAbout = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StoreAbout");
                OnStoreAboutChanged();
            }
        }
        private global::System.String _StoreAbout;
        partial void OnStoreAboutChanging(global::System.String value);
        partial void OnStoreAboutChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StoreRecordDate
        {
            get
            {
                return _StoreRecordDate;
            }
            set
            {
                OnStoreRecordDateChanging(value);
                ReportPropertyChanging("StoreRecordDate");
                _StoreRecordDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StoreRecordDate");
                OnStoreRecordDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _StoreRecordDate;
        partial void OnStoreRecordDateChanging(Nullable<global::System.DateTime> value);
        partial void OnStoreRecordDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StoreEstablishmentDate
        {
            get
            {
                return _StoreEstablishmentDate;
            }
            set
            {
                OnStoreEstablishmentDateChanging(value);
                ReportPropertyChanging("StoreEstablishmentDate");
                _StoreEstablishmentDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StoreEstablishmentDate");
                OnStoreEstablishmentDateChanged();
            }
        }
        private Nullable<global::System.Int32> _StoreEstablishmentDate;
        partial void OnStoreEstablishmentDateChanging(Nullable<global::System.Int32> value);
        partial void OnStoreEstablishmentDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> StoreCapital
        {
            get
            {
                return _StoreCapital;
            }
            set
            {
                OnStoreCapitalChanging(value);
                ReportPropertyChanging("StoreCapital");
                _StoreCapital = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StoreCapital");
                OnStoreCapitalChanged();
            }
        }
        private Nullable<global::System.Byte> _StoreCapital;
        partial void OnStoreCapitalChanging(Nullable<global::System.Byte> value);
        partial void OnStoreCapitalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> StoreEmployeesCount
        {
            get
            {
                return _StoreEmployeesCount;
            }
            set
            {
                OnStoreEmployeesCountChanging(value);
                ReportPropertyChanging("StoreEmployeesCount");
                _StoreEmployeesCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StoreEmployeesCount");
                OnStoreEmployeesCountChanged();
            }
        }
        private Nullable<global::System.Byte> _StoreEmployeesCount;
        partial void OnStoreEmployeesCountChanging(Nullable<global::System.Byte> value);
        partial void OnStoreEmployeesCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> StoreEndorsement
        {
            get
            {
                return _StoreEndorsement;
            }
            set
            {
                OnStoreEndorsementChanging(value);
                ReportPropertyChanging("StoreEndorsement");
                _StoreEndorsement = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StoreEndorsement");
                OnStoreEndorsementChanged();
            }
        }
        private Nullable<global::System.Byte> _StoreEndorsement;
        partial void OnStoreEndorsementChanging(Nullable<global::System.Byte> value);
        partial void OnStoreEndorsementChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> StoreType
        {
            get
            {
                return _StoreType;
            }
            set
            {
                OnStoreTypeChanging(value);
                ReportPropertyChanging("StoreType");
                _StoreType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StoreType");
                OnStoreTypeChanged();
            }
        }
        private Nullable<global::System.Byte> _StoreType;
        partial void OnStoreTypeChanging(Nullable<global::System.Byte> value);
        partial void OnStoreTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PurchasingDepartmentName
        {
            get
            {
                return _PurchasingDepartmentName;
            }
            set
            {
                OnPurchasingDepartmentNameChanging(value);
                ReportPropertyChanging("PurchasingDepartmentName");
                _PurchasingDepartmentName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PurchasingDepartmentName");
                OnPurchasingDepartmentNameChanged();
            }
        }
        private global::System.String _PurchasingDepartmentName;
        partial void OnPurchasingDepartmentNameChanging(global::System.String value);
        partial void OnPurchasingDepartmentNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PurchasingDepartmentEmail
        {
            get
            {
                return _PurchasingDepartmentEmail;
            }
            set
            {
                OnPurchasingDepartmentEmailChanging(value);
                ReportPropertyChanging("PurchasingDepartmentEmail");
                _PurchasingDepartmentEmail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PurchasingDepartmentEmail");
                OnPurchasingDepartmentEmailChanged();
            }
        }
        private global::System.String _PurchasingDepartmentEmail;
        partial void OnPurchasingDepartmentEmailChanging(global::System.String value);
        partial void OnPurchasingDepartmentEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GeneralText
        {
            get
            {
                return _GeneralText;
            }
            set
            {
                OnGeneralTextChanging(value);
                ReportPropertyChanging("GeneralText");
                _GeneralText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GeneralText");
                OnGeneralTextChanged();
            }
        }
        private global::System.String _GeneralText;
        partial void OnGeneralTextChanging(global::System.String value);
        partial void OnGeneralTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HistoryText
        {
            get
            {
                return _HistoryText;
            }
            set
            {
                OnHistoryTextChanging(value);
                ReportPropertyChanging("HistoryText");
                _HistoryText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HistoryText");
                OnHistoryTextChanged();
            }
        }
        private global::System.String _HistoryText;
        partial void OnHistoryTextChanging(global::System.String value);
        partial void OnHistoryTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FounderText
        {
            get
            {
                return _FounderText;
            }
            set
            {
                OnFounderTextChanging(value);
                ReportPropertyChanging("FounderText");
                _FounderText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FounderText");
                OnFounderTextChanged();
            }
        }
        private global::System.String _FounderText;
        partial void OnFounderTextChanging(global::System.String value);
        partial void OnFounderTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhilosophyText
        {
            get
            {
                return _PhilosophyText;
            }
            set
            {
                OnPhilosophyTextChanging(value);
                ReportPropertyChanging("PhilosophyText");
                _PhilosophyText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PhilosophyText");
                OnPhilosophyTextChanged();
            }
        }
        private global::System.String _PhilosophyText;
        partial void OnPhilosophyTextChanging(global::System.String value);
        partial void OnPhilosophyTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> ViewCount
        {
            get
            {
                return _ViewCount;
            }
            set
            {
                OnViewCountChanging(value);
                ReportPropertyChanging("ViewCount");
                _ViewCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ViewCount");
                OnViewCountChanged();
            }
        }
        private Nullable<global::System.Int64> _ViewCount;
        partial void OnViewCountChanging(Nullable<global::System.Int64> value);
        partial void OnViewCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> SingularViewCount
        {
            get
            {
                return _SingularViewCount;
            }
            set
            {
                OnSingularViewCountChanging(value);
                ReportPropertyChanging("SingularViewCount");
                _SingularViewCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SingularViewCount");
                OnSingularViewCountChanged();
            }
        }
        private Nullable<global::System.Int64> _SingularViewCount;
        partial void OnSingularViewCountChanging(Nullable<global::System.Int64> value);
        partial void OnSingularViewCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> StoreShowcase
        {
            get
            {
                return _StoreShowcase;
            }
            set
            {
                OnStoreShowcaseChanging(value);
                ReportPropertyChanging("StoreShowcase");
                _StoreShowcase = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StoreShowcase");
                OnStoreShowcaseChanged();
            }
        }
        private Nullable<global::System.Boolean> _StoreShowcase;
        partial void OnStoreShowcaseChanging(Nullable<global::System.Boolean> value);
        partial void OnStoreShowcaseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StorePicture
        {
            get
            {
                return _StorePicture;
            }
            set
            {
                OnStorePictureChanging(value);
                ReportPropertyChanging("StorePicture");
                _StorePicture = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StorePicture");
                OnStorePictureChanged();
            }
        }
        private global::System.String _StorePicture;
        partial void OnStorePictureChanging(global::System.String value);
        partial void OnStorePictureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OrderCode
        {
            get
            {
                return _OrderCode;
            }
            set
            {
                OnOrderCodeChanging(value);
                ReportPropertyChanging("OrderCode");
                _OrderCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OrderCode");
                OnOrderCodeChanged();
            }
        }
        private global::System.String _OrderCode;
        partial void OnOrderCodeChanging(global::System.String value);
        partial void OnOrderCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> storerate
        {
            get
            {
                return _storerate;
            }
            set
            {
                OnstorerateChanging(value);
                ReportPropertyChanging("storerate");
                _storerate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("storerate");
                OnstorerateChanged();
            }
        }
        private Nullable<global::System.Decimal> _storerate;
        partial void OnstorerateChanging(Nullable<global::System.Decimal> value);
        partial void OnstorerateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ProductCount
        {
            get
            {
                return _ProductCount;
            }
            set
            {
                OnProductCountChanging(value);
                ReportPropertyChanging("ProductCount");
                _ProductCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductCount");
                OnProductCountChanged();
            }
        }
        private Nullable<global::System.Int32> _ProductCount;
        partial void OnProductCountChanging(Nullable<global::System.Int32> value);
        partial void OnProductCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> ReadyForSale
        {
            get
            {
                return _ReadyForSale;
            }
            set
            {
                OnReadyForSaleChanging(value);
                ReportPropertyChanging("ReadyForSale");
                _ReadyForSale = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReadyForSale");
                OnReadyForSaleChanged();
            }
        }
        private Nullable<global::System.Boolean> _ReadyForSale;
        partial void OnReadyForSaleChanging(Nullable<global::System.Boolean> value);
        partial void OnReadyForSaleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StoreUniqueShortName
        {
            get
            {
                return _StoreUniqueShortName;
            }
            set
            {
                OnStoreUniqueShortNameChanging(value);
                ReportPropertyChanging("StoreUniqueShortName");
                _StoreUniqueShortName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StoreUniqueShortName");
                OnStoreUniqueShortNameChanged();
            }
        }
        private global::System.String _StoreUniqueShortName;
        partial void OnStoreUniqueShortNameChanging(global::System.String value);
        partial void OnStoreUniqueShortNameChanged();

        #endregion

    
    }

    #endregion

    
}
